### ISSUE TITLE
Cannot load parseconfig on Linux

### ISSUE THREAD

**Issue by cacharle** [hivehelsinki/norminette-client#1]
After running `bundle install --path ./vendor/bundle`, I get the following error when I try to run `norminette.rb`

```
Traceback (most recent call last):
        2: from ./norminette.rb:5:in `<main>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- parseconfig (LoadError)
```

I 'fixed' it by hardcoding the default value of `config.conf` in the script.

**Comment by jgengo** [comment]
Hello @HappyTramp ! 

Could you please specify :

- your OS / distro
- ruby and bundle version

Did you follow step by step the instructions of your OS?

**Comment by cacharle** [comment]
```
❯ uname -a
Linux charleslaptop 5.4.27-1-MANJARO #1 SMP PREEMPT Sat Mar 21 16:33:27 UTC 2020 x86_64 GNU/Linux

❯ ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]

❯ bundler --version
Bundler version 2.1.4
```

It works when in install the dependencies in the global scope.
I just needed to add the path to load parseconfig:
`ruby -I ./vendor/bundle/ruby/2.7.0/gems/parseconfig-1.0.8/lib/ norminette.rb`
It's weird that bundler path isnt load by default tho.
Sorry for the waste of time

**Comment by jgengo** [comment]
Thanks for letting me know.

Have a nice day.
-Jordane

**Comment by benjaminmerchin** [comment]
> ```
> ❯ uname -a
> Linux charleslaptop 5.4.27-1-MANJARO #1 SMP PREEMPT Sat Mar 21 16:33:27 UTC 2020 x86_64 GNU/Linux
> 
> ❯ ruby --version
> ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
> 
> ❯ bundler --version
> Bundler version 2.1.4
> ```
> 
> It works when in install the dependencies in the global scope.
> I just needed to add the path to load parseconfig:
> `ruby -I ./vendor/bundle/ruby/2.7.0/gems/parseconfig-1.0.8/lib/ norminette.rb`
> It's weird that bundler path isnt load by default tho.
> Sorry for the waste of time

Hi, I just had exactly the same issue on macOS and found your answer. I finally found the reason after a long time while trying your solution : I had forgotten to enter "bundle" in the terminal. I guess it is the way to set the path. So if anyone else has the same issue for their norminette the solution is just to enter "bundle". Have a nice day !

**Comment by woodstock1993** [comment]
I have installation error when installing norminette in local.
I also some opinions written above and other resources but can't handle properly.
Please help me how to fix my problem. Plus I'm really a novice to computer. 
Here is my information with error information

☁  ~  uname -a
Darwin seojaehwan-ui-MacBookPro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64

☁  ~  ruby --version
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [arm64-darwin20]

☁  ~  bundler --version
Bundler version 2.2.15☁

☁  ~  cd .norminette
☁  .norminette  ./norminette.rb
<internal:/Users/sjh/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- parseconfig (LoadError)
Did you mean?  rbconfig
	from <internal:/Users/sjh/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from ./norminette.rb:5:in `<main>'
