### ISSUE TITLE
Fix indentation/alignment and add a license

### ISSUE THREAD

**Issue by adri326** [hivehelsinki/norminette-client#3]
Since this project's source code seems to be spread out between several projects, I will mention here the issue made on 42Paris/norminette about the tabulation/whitespace madness in `norminette.rb`:

https://github.com/42Paris/norminette/issues/5

My second point is that [**you should always give a license to the code that you share.**](https://opensource.guide/starting-a-project/)

**Comment by jgengo** [comment]
Hello,

This client has been written by 42 a long time ago. It's gonna be complicated for me to decide on a license.

But I will fix the tabulations/ident issues.
Thank you for your report.
